FactoryBot.define do
  factory :status do
    uid {123}
    screen_name {'status_sn'}
    status_info {{id: 12345, text: 'status text'}.to_json}

    factory :mention_status do
      status_info {"{\"created_at\":\"Sun Apr 09 14:57:00 +0000 2017\",\"id\":851086549508685824,\"text\":\"@PoyoMetal メンションです。\",\"source\":\"\\u003ca href=\\\"http://twitter.com/download/android\\\" rel=\\\"nofollow\\\"\\u003eTwitter for Android\\u003c/a\\u003e\",\"truncated\":false,\"coordinates\":null,\"place\":null,\"entities\":{\"hashtags\":[],\"symbols\":[],\"user_mentions\":[{\"screen_name\":\"PoyoMetal\",\"name\":\"PØYO🌸\",\"id\":1001668814,\"id_str\":\"1001668814\",\"indices\":[0,10]}],\"urls\":[]},\"user\":{\"id\":58135830,\"id_str\":\"58135830\",\"name\":\"さいころ\",\"screen_name\":\"ts_3156\",\"location\":\"どん底は大草原♪\",\"description\":\"明るい方に泳いでいきたい(^ ^) synaesthesia.jp http://t.co/Xfz5dHnbeZ\",\"url\":\"http://t.co/4k8XZeoB84\",\"entities\":{\"url\":{\"urls\":[{\"url\":\"http://t.co/4k8XZeoB84\",\"expanded_url\":\"http://hivecolor.com/\",\"display_url\":\"hivecolor.com\",\"indices\":[0,22]}]},\"description\":{\"urls\":[{\"url\":\"http://t.co/Xfz5dHnbeZ\",\"expanded_url\":\"http://egotter.com\",\"display_url\":\"egotter.com\",\"indices\":[34,56]}]}},\"protected\":true,\"followers_count\":921,\"friends_count\":395,\"listed_count\":100,\"created_at\":\"Sun Jul 19 05:52:19 +0000 2009\",\"favourites_count\":507,\"utc_offset\":32400,\"time_zone\":\"Tokyo\",\"geo_enabled\":false,\"verified\":false,\"statuses_count\":51176,\"lang\":\"ja\",\"contributors_enabled\":false,\"is_translator\":false,\"is_translation_enabled\":true,\"profile_background_color\":\"C0DEED\",\"profile_background_image_url\":\"http://abs.twimg.com/images/themes/theme1/bg.png\",\"profile_background_image_url_https\":\"https://abs.twimg.com/images/themes/theme1/bg.png\",\"profile_background_tile\":false,\"profile_image_url\":\"http://pbs.twimg.com/profile_images/794776255795118080/8T2gY60M_normal.jpg\",\"profile_image_url_https\":\"https://pbs.twimg.com/profile_images/794776255795118080/8T2gY60M_normal.jpg\",\"profile_banner_url\":\"https://pbs.twimg.com/profile_banners/58135830/1364757455\",\"profile_link_color\":\"1DA1F2\",\"profile_sidebar_border_color\":\"C0DEED\",\"profile_sidebar_fill_color\":\"DDEEF6\",\"profile_text_color\":\"333333\",\"profile_use_background_image\":true,\"has_extended_profile\":false,\"default_profile\":true,\"default_profile_image\":false,\"following\":false,\"follow_request_sent\":false,\"notifications\":false,\"translator_type\":\"regular\"},\"contributors\":null,\"is_quote_status\":false,\"retweet_count\":0,\"favorite_count\":0,\"favorited\":false,\"retweeted\":false,\"lang\":\"ja\"}"}
    end
  end
end
