# docker-compose build --no-cache
# docker-compose up
# docker-compose run --rm web bundle install --path /usr/local/bundle

version: "3"

services:
  redis:
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./setup/etc/redis.dev.conf:/etc/redis.conf
    deploy:
      resources:
        limits:
          memory: 64M
  redis2:
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./setup/etc/redis.dev.conf:/etc/redis.conf
    hostname: redis2
    deploy:
      resources:
        limits:
          memory: 64M
  web:
    build: .
    working_dir: /home/root/egotter
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - bundle:/usr/local/bundle
      - .:/home/root/egotter:cached
      - ~/.aws:/root/.aws
      - /tmp/mysql.sock:/tmp/mysql.sock
    ports:
      - "3000:3000"
      - "3035:3035"
    deploy:
      resources:
        limits:
          memory: 512M
  sidekiq:
    build: .
    working_dir: /home/root/egotter
    command: bundle exec sidekiq -C config/sidekiq_dev.yml
    volumes:
      - bundle:/usr/local/bundle
      - .:/home/root/egotter:cached
      - ~/.aws:/root/.aws
      - /tmp/mysql.sock:/tmp/mysql.sock
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 512M
volumes:
  bundle:
