- 'えごったー知ってる？？ 仲良しとかツイートの分析ができて面白いよ！ ٩(๑❛ᴗ❛๑)۶'
- 'えごったーっていうの使えば一瞬で誰にリムられたかとかわかるよ！🥳'
- 'えごったーすごいΣ(-᷅_-᷄๑)'
- 'えごったーのおかげでリムった人のID付きでDMくるの有能🥺'
- 'メンヘラにはえごったーさいきょう🥺'
- 'すげぇ今日誰にもリムられなかったwww'
- |
  えごったー 面白い🤭😂
  ランキングや個性の分析まである😘👍
- 'えごったー天才だた、😳'
- |
  えごったー？？ みたいなのをフォローしたらリム通知送ってくれますよ！！
  最高です、これw
- 'えごったー便利くね'
- 'えごったー誰かが僕のこと検索したら通知来るんだけど神'
- 'えごったーってすごいね'
- 'えごったー最強ですね'
- 'えごったー神'
- 'えごったーめちゃめちゃ便利で草'
- 'えごったーのツイートだいすこ'
- 'めっちゃリムられたが？？？？？？えごったー万能スギィ'
- 'えごったーつけてるからすぐわかりまぁす'
- 'えごったーはほんとにええぞ、便利だ。'
- 'えごったー…結構便利だけどDM通知に毎回ビビる_(┐「ε:)_'
- '私をえごったーで検索するな😇'
- 'えごったーすき( ⸝⸝⸝ᵕᴗᵕ⸝⸝⸝ )'
- 'このえごったーてやつまじ万能w'
- |
  えごったーって便利やね
  リムった奴の名前と垢わかるから
- 'えごったーすごい'
- 'えごったーさんめちゃめちゃ便利で助かってます( ⸝⸝⸝ᵕᴗᵕ⸝⸝⸝ )'
- 'えごったーでわたしのこと調べた人誰やねんw ₍ᐡ- -ᐡ₎'
- 'えごったーほんとに便利だ'
- |
  えごったーおすすめ()
  リムられ通知まじ有能…!!!
- 'えごったーおもろいꉂꉂ(ᵔᗜᵔ*)'
- 'えごったー (๑ ิټ ิ)ﾍﾍｯ'
- 'えごったー大好き'
- 'えごったー有能過ぎる…(੭;´ ꒫`)੭'
- 'えごったーくんこんな機能ありましたっけ？？愛しいな🥳💓'
- 'リムとかブロックの確認はえごったー使ってるよ～過去にさかのぼっては見れないかもしれないけど垢消しした人ひと目でわかるから突然いなくなってもわかるし便利だよ'
- |
  リムられ通知はね、
  ①検索で「えごったー」と調べる
  ②で、プロフに載ってる「リム通知登録」のURLをタップ
  ③そこからログインする(ログイン手順はやったら分かる笑)

  ってしたら、出来るよ〜！
  私はDMに通知来るようにしてる〜！
- 'リムるならフォローしないで下さい⸜( ‵_′ )⸝えごったーで分かるんですからね！あ、ちなみにリムバ100ですw'
- |
  えごったーは聖書
  毎日決まった時間に見ろ
- 'えごったー面白いねwww'
- |
  えごったアアア！！！
  私は愛用しているぞォー！
  元は誤動作でフォロー解除してしまった人を探す為に導入したが、今はきちんと、フォロー解除された人を毎日確認出来ている！！！(泣)
- 'えごったー使いやすくなってて嬉しい'
- |
  えごったー素敵w

  リムったやつすぐわかるw
- 'えごったー（ @ego_tter ）私はコレ使ってますよ！'
- |
  えごったーが進化したぞ！　見所ありまくりなんですけど笑
  好きなんですわ笑　えごったー
  片想われとか片想いを見るのが楽しい！　フォロー返され率まで見れる
  使う人増えるといいなぁ
- 'えごったー使うと垢消しとか秒で分かるけど、人が消えていくのを見るのは悲しいわね'
- 'えごったーあると便利'
- 'えごったー便利ぃぃぃぃぃぃぃぃ↑'
- 'コレ便利リムった人わかるからブロックできるぜ❤'
- 'えごったー便利すぎるね。'
- 'えごったー有能すぎ'
- 'えごったー便利だわ、本当に垢消しだった、、、'
- 'えごったーちょーべんり'
- 'えごったー見たらブロされてる人33もいて悲しくなった…'
- 'えごったーで確認したらブロられてるの8人www ｳｪｲ'
- '私はえごったー使ってる！！！リムられたらDMくる✌🏻✌🏻✌🏻'
- 'えごったーちゃん、知らない誰かでもブロックされてたらこいつにブロックされてるやで～って教えてくれるのめっちゃ偉いやん。'
- 'えごったー面白い'
- |
  リムられたとかわかるんだ、、
  ミュートさえわかるんだ、、
  ビックリ、、、
- |
  リムられたらえごったーに頼るといいで
  誰にリムられたか分かるから
  って言う宣伝((
- 'えごったーでみれる'
- 'えごったーからなんか4人にリムられましたって来たんだけどww'
- '夏くらいからえごったー入れてるからリムやブロ解関係は誰だか解るんだけど、相互さん減ったなと思うとだいたい垢消しよね'
- |
  えごったー使ってみたら
  27人ぐらいにブロされてたwww
- |
  最近リムル人多くて悲しい号泣
  誰リムったかわからないのでえごったー使ってリムった人探すの最強です！
- 'えごったー使ってるからリムられたか分かるぞ、1人リムられたよ、'
- |
  知ってる人いると思いますが、えごったーでマイトップファンのような機能があるのはご存知ですか？
  アプリを入れるのが面倒、制限でアプリを入れられないという方はえごったーからやってみてください！ほぼ出来ることは同じなのでオススメです👍🏻
- 'えごったーすごい使えるwリムられたらすぐ対応できて便利(*＾▽＾*)それにしてもめちゃくちゃリムられるなあ！Σ(￣□￣;)'
- 'ＴＬで流れてきた、えごったー、すごい…'
- 'えごったーすげー。'
- |
  えごったー私も入れてみた。
  フォロー解除とかアプリ入れればバレバレなんだよなぁ…
- 'えごったーつけてるよ✨'
- |
  えごったーってのを使い始めたんだけど怖すぎなこれw リムられたとかわかっちゃうのかよww

  つかリアルの知り合い以外でも普通にブロックされてた🥺
- '皆がよくやってるフォロワー❤で表示するやつえごったーだったのか！'
- 'えごったー便利だな。もっと早くから使っとけばよかた'
- '久しぶりにえごったーみたら私垢消しされた事になってるんですけどぉぉヾ(・ω・`;)ﾉ'
- 'えごったーべんり'
- 'えごったーやってみた'
- 'えごったー適当に見てたら次々見つかって草'
- |
  えごったー「リムられてるやで〜」

  僕「このID見たことないな…誰やろ」

  Twitter「こいつのフォローにフォロワーいないしブロられてるやで」

  僕「いやマジで誰・・・？（困惑）」
- '一日で2人から切られたけどな！おれえごったーやってるから切ったやつわかる'
- |
  えごったー登録したのでリムった方分かります大爆笑

  リムしたアカウントが見えるからブロックしたくなっちゃうけど優しいからしなーい
- 'えごったー使ってるから誰がブロックしたかわかるw'
- '垢消し多すぎww'
- 'えごったー久しぶりに見たら垢消してリムられた人には「垢消し？」って書いててめっちゃ便利になってる…'
- 'えごったー入れたのでリムった人ブロックします😍😍😍'
- |
  んふふ、んふふふふふ、えごったー使ったらどちゃくそリムった人分かるまじ卍🥺🥺🥺🥺
  これツイートすると2回分検索できるようになるとかまじわろた🥺🥺🥺🥺🥺🥺🥺
- 'えごったー便利だよ、ログインしてリムられ通知オンにするだけで誰にリムられたかとか垢消し、凍結も分かっちゃうから把握するのにめちゃ楽。'
- 'えごったーって初めて使ったけどすごいね!!!'
- |
  めっちゃリムられてるw
  しかし、えごったーで調べたら誰がリムったか一目瞭然！結構身近な人がリムってて愕然とした！
  リムった人！もう二度と絡むこともないから永遠にばいばい(๑•᎑•๑)ﾉｼ
- 'えごったーがいればあんしん🥺'
- 'えごったーってやつにウェブからログインしていろいろすればリム通知ON！(語彙力)'
- 'てか私えごったー入れてるからリムられたらすぐわかる、、'
- 'えごったーってアプリまじでなんか便利だよな…'
- 'えごったーやってて気がついた……'
- 'リムられたら誰がリムったかDMで通知くるようにできるよ！片思い、片思われもわかるから、リムばフォロバしやすいよ！'
- 'えごったー最強すぎる'
