<% require 'dotenv/load' %>:concurrency: <%= ENV.fetch("SIDEKIQ_MISC_CONCURRENCY") { 5 } %>
:timeout: 300
:pidfile: ./tmp/pids/sidekiq_misc_<%= ENV.fetch("WORKER_INDEX") { "NOINDEX" } %>.pid
:logfile: ./log/sidekiq_misc.log
:tag:
  - sidekiq_misc
  - <%= ENV.fetch("AWS_NAME_TAG") { "NONAME" } %>
  - <%= 'WORKER_' + ENV.fetch("WORKER_INDEX") { "NOINDEX" } %>
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - creating_high
  - deleting_high
  - webhook
  - logging
  - messaging
  - misc
  - creating_low
  - deleting_low
  - follow
  - unfollow
  - misc_low
  - report_high
  - CreateHighPriorityTwitterDBUserWorker
  - CreateTwitterDBUserWorker
  - CreateTwitterDBUserForRetryingDeadlockWorker
  - ImportTwitterDBUserWorker
  - report_low
  - retry_low
  - CreateReportTwitterUserWorker
