<% require 'dotenv/load' %>:concurrency: 5
:timeout: 5
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:tag:
  - sidekiq
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - creating_high
  - deleting_high
  - webhook
  - logging
  - messaging
  - misc
  - creating_low
  - deleting_low
  - report_high
  - AssembleTwitterUserWorker
  - ImportTwitterDBUserWorker
  - CreateTwitterDBUserWorker
  - CreateTwitterUserWorker
  - CreateReportTwitterUserWorker
  - WriteToS3Worker
  - import
  - follow
  - unfollow
  - misc_low
  - report_low
  - retry_low
  - batch
