#!/bin/sh

# /etc/init.d/unicorn

if [ -f /etc/init.d/functions ]; then
  . /etc/init.d/functions
fi

if echo ' \c' | grep 'c' > /dev/null 2>&1; then
  en='-n'
  ec=''
else
  en=''
  ec='\c'
fi

APP_ROOT="/home/ec2-user/egotter/"
USER="ec2-user"

start() {
  /etc/init.d/unicorn start && \
  /etc/init.d/sidekiq_delayed_create start && \
  /etc/init.d/sidekiq start && \
  /etc/init.d/sidekiq_import start && \
  /etc/init.d/sidekiq_logging start && \
  /etc/init.d/sidekiq_misc start
}

stop() {
  /etc/init.d/unicorn stop && \
  /etc/init.d/sidekiq_delayed_create stop && \
  /etc/init.d/sidekiq stop && \
  /etc/init.d/sidekiq_import stop && \
  /etc/init.d/sidekiq_logging stop && \
  /etc/init.d/sidekiq_misc stop
}

restart() {
  /etc/init.d/unicorn restart && \
  /etc/init.d/sidekiq_delayed_create restart && \
  /etc/init.d/sidekiq restart && \
  /etc/init.d/sidekiq_import restart && \
  /etc/init.d/sidekiq_logging restart && \
  /etc/init.d/sidekiq_misc restart
}

rh_status() {
  cd $APP_ROOT
  cmd1="ps x -o pid,command | grep unicorn | grep -v grep"
  if ls ${APP_ROOT}/tmp/pids/sidekiq*.pid >/dev/null 2>&1; then
    cmd2='ps -o pid=,command= -p $(cat ${APP_ROOT}tmp/pids/sidekiq*.pid)'
  else
    cmd2=":"
  fi
  sudo -u ${USER} -H bash -l -c "cd $APP_ROOT && ${cmd1} && ${cmd2}"
}

case "$1" in
  start)
          start
          ;;
  stop)
          stop
          ;;
  restart)
          restart
          ;;
  status)
          rh_status
          ;;
  *)
          echo "Usage: egotter {restart|status}" >&2
          exit 1
          ;;
esac
exit 0

