#!/bin/sh

if [ -f /etc/init.d/functions ]; then
  . /etc/init.d/functions
fi

if echo ' \c' | grep 'c' >/dev/null 2>&1; then
  en='-n'
  ec=''
else
  en=''
  ec='\c'
fi

APP_ROOT="/var/egotter/"

do_start() {
  /etc/init.d/puma start
  start sidekiq
  start sidekiq_import
  start sidekiq_misc
  start sidekiq_prompt_reports
}

do_stop() {
  /etc/init.d/puma stop
  stop sidekiq
  stop sidekiq_import
  stop sidekiq_misc
  stop sidekiq_prompt_reports
}

rh_status() {
  cmd1=":"
  if ls ${APP_ROOT}/tmp/pids/puma.pid >/dev/null 2>&1; then
    cmd1="ps x -o pid,command | grep puma | grep -v grep"
  fi

  cmd2=":"
  if ls ${APP_ROOT}/tmp/pids/sidekiq*.pid >/dev/null 2>&1; then
    cmd2='ps -o pid=,command= -p$(cat ${APP_ROOT}tmp/pids/sidekiq*.pid)'
  fi

  sh -c "cd $APP_ROOT && ${cmd1} ; ${cmd2}"
}

case "$1" in
start)
  do_start
  ;;
stop)
  do_stop
  ;;
status)
  rh_status
  ;;
*)
  echo "Usage: egotter {start|stop|status}" >&2
  exit 2
  ;;
esac
