#!/bin/sh

# chkconfig: 345 85 15
# description: sidekiq_prompt_reports

# You must call ulimit in this file rather than patient_sidekiqctl.rb as this command affects processes spawned by this shell.
ulimit -n 4096

/etc/init.d/patient_sidekiqctl.rb -e production --dir /var/egotter --user ec2-user --name sidekiq_prompt_reports --state $1
